# Generated by Django 5.1.1 on 2025-11-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENTE', 'Cliente'), ('CHOFER', 'Chofer')], max_length=10)),
                ('key', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('role', 'key')},
            },
        ),
    ]
